package ledger.io.input;


import au.com.bytecode.opencsv.CSVReader;
import ledger.database.entity.Account;
import ledger.database.entity.Transaction;
import ledger.exception.ConverterException;

import java.io.File;
import java.util.List;

/**
 * Takes a CSV file generated by PayPal and converts into Ledger Object Structure
 **/
public class PayPalCSVConverter extends AbstractCSVConverter {

    public PayPalCSVConverter(File file, Account account) {
        super(file, account);
    }

    @Override
    protected List<Transaction> readFile(CSVReader reader) throws ConverterException {
        return null;
    }
}
